### PR TITLE
Update PollReceiver.java

### PR DESCRIPTION
**Pull request by anhourglass**
This may have been an error

### CODE REVIEW

**Comment by commonsguy** [comment]
Correct! Many thanks! Due to some other in-flight work, I am electing to make this edit manually on my machine rather than merge in your pull request. I'll be pushing up the repaired version when I release Version 6.9 of my book, before the end of the month.

Thanks again!

**Comment by IgorGanapolsky** [comment]
I thought you said you do not accept pull requests on this repo?

**Comment by commonsguy** [comment]
@IgorGanapolsky As you will note, I did not accept the pull request.

**Comment by anhourglass** [comment]
No problem. That project was very helpful for me to quickly get some tests
going to play with doze, so thank you. I'll be getting a warescription soon.

- Alex

**Pull request closed without merging**
