### PR TITLE
Rebuild with latest Gradle version. Reformat code. Fix build error in AndroidManifest.

### PR DESCRIPTION
**Pull request by IgorGanapolsky**
Rebuild with latest Gradle version.
Reformat code.
Fix build error in AndroidManifest.

### CODE REVIEW

**Comment by commonsguy** [comment]
"Rebuild with latest Gradle version" -- there is nothing in your pull request that changes the Gradle version.

"Reformat code" -- I would prefer to maintain consistency with the rest of my samples.

"Fix build error in AndroidManifest" -- I fail to see what in this pull request would have this effect.

**Comment by IgorGanapolsky** [comment]
I changed  android:targetSdkVersion="21", which makes this Lollipop compatible.  Furthermore, I added Material theme in the <application> tag.  Lastly, I added:
`<uses-sdk
       android:targetSdkVersion="21"
       android:minSdkVersion="16"
        tools:overrideLibrary="com.commonsware.android.advservice.binding" />
`
In order to fix build error with support-v13 conflicts.

**Comment by IgorGanapolsky** [comment]
~" I would prefer to maintain consistency with the rest of my samples."
But your entire code samples are not formatted in Android Studio.  Wouldn't it be better to format it like the IDE says instead of free-styling it without adhering to standards?

**Comment by commonsguy** [comment]
"I changed android:targetSdkVersion="21", which makes this Lollipop compatible" -- the `AdvServices/` samples are old, replaced by the ones in the `Binding/` directory for the purposes of my book. These are left here for historical purposes (e.g., inbound links), with [a `README` that explains this](https://github.com/commonsguy/cw-omnibus/tree/master/AdvServices).

"Wouldn't it be better to format it like the IDE says instead of free-styling it without adhering to standards?" -- no, for any number of reasons, not the least of which that this code goes in a book, and books in print and PDF form have line length limitations.

**Pull request closed without merging**
